# Generated by Django 4.1.4 on 2022-12-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inform_sys_selective_subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва дисципліни')),
                ('level', models.CharField(choices=[('b', 'перший(бакалаврський)'), ('m', 'другий(магістерський)'), ('p', 'третій(освітньо-науковий)')], default='b', max_length=1, verbose_name='Рівень ВО')),
                ('language', models.CharField(default='українська', max_length=30, verbose_name='Мова викладання')),
                ('preconditions', models.CharField(default='Немає', max_length=120, verbose_name='Пререквізити (передумови вивчення дисципліни)')),
                ('what_is_being_studied', models.CharField(max_length=150, verbose_name='Що буде вивчатися')),
                ('why_should_be_studied', models.CharField(max_length=150, verbose_name='Чому це цікаво/треба вивчати')),
                ('what_can_be_learned', models.CharField(max_length=180, verbose_name='Чого можна навчитися (результати навчання)')),
                ('how_to_use', models.CharField(max_length=150, verbose_name='Як можна користуватися набутими знаннями і уміннями (компетентності)')),
                ('information_provision', models.CharField(max_length=150, verbose_name='Інформаційне забезпечення')),
                ('educational_activities_type', models.CharField(max_length=100, verbose_name='Види навчальних занять (лекції, практичні, семінарські, лабораторні заняття тощо')),
                ('semester_control_type', models.CharField(max_length=30, verbose_name='Вид семестрового контролю')),
                ('max_capacity', models.PositiveSmallIntegerField(blank=True, verbose_name='Максимальна кількість здобувачів')),
                ('min_capacity', models.PositiveSmallIntegerField(blank=True, verbose_name='Мінімальна кількість здобувачів')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inform_sys_selective_subjects.department', verbose_name='Кафедра')),
                ('lecturer', models.ManyToManyField(blank=True, to='inform_sys_selective_subjects.lecturer')),
                ('majoring', models.ManyToManyField(to='inform_sys_selective_subjects.majoring', verbose_name='Рекомендується для галузі знань (спеціальності, освітньої програми)')),
                ('semester', models.ManyToManyField(to='inform_sys_selective_subjects.semester')),
            ],
            options={
                'verbose_name': 'Вибіркова дисципліна',
                'verbose_name_plural': 'Вибіркові дисципліни',
            },
        ),
    ]
